### ISSUE TITLE
Sources for unknowns

### ISSUE THREAD

**Issue by 676339784** [CamilleScholtz/ricespo#1]
- [Unknown 7](http://camillescholtz.nl/ricespo/assets/images/rice/full/unknown_7.png) and [Unknown 9](http://camillescholtz.nl/ricespo/assets/images/rice/full/unknown_9.png) belong to [dkeg](https:reddit.com/u/dkeg)
- [Unknown 14](http://camillescholtz.nl/ricespo/assets/images/rice/full/unknown_14.png) belongs to [mobo](https://www.reddit.com/r/unixporn/comments/32d87j/openboxlablakely_dress/)

**Comment by CamilleScholtz** [comment]
Fixed, thanks.

**Comment by 676339784** [comment]
Another one:
- [Unknown 13](https://www.reddit.com/r/unixporn/comments/2ugwbv/thanks_venam_smutt_hopps/) belongs to dkeg
